language: node_js
node_js:
  - "9.11.1"

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master
