language: node_js
node_js:
  - "10.4.0"

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master
